name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: get htmixer
      run: git clone https://github.com/liyanboy74/htmixer.git

    - name: build & install htmixer
      run: cd htmixer && mkdir build && cd build && cmake .. && make && make install && cd ..
      
    - name: get smg
      run: git clone https://github.com/liyanboy74/smg.git

    - name: build & install smg
      run: cd smg && mkdir build && cd build && cmake .. && make && make install && cd ..

    - name: make
      run: make
      
